FROM python:3.10.9

RUN apt-get updates
RUN apt-get install -y python3-pip
RUN pip3 install numpy pandas matplotlib seaborn 

#Run the following line to build the image
#docker build -t DataScie_Ex5_image . 